[project]
name = "aoc-proofing-repo"
version = "0.1.0"
description = "A learning resource for the community"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "networkx>=3.4.2",
    "notepad>=1.3.5",
]
